# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, page, url, pre, weight.



# Add a trailing '/' to local URLs.
# For example: /posts/
# NOT: /posts

# `pre` is an icon ID. For a list of all available icons, check [https://github.com/mnjm/kayal/tree/main/assets/icons]

[[main]]
name = "sowndarya Krishnan"
title = "Home"
url = "/"
weight = 1



#
[[main]]
name = "about"
title = "About"
url = "/about/"
weight = 2

#
[[main]]
name = "Portfolio"
title = "Portfolio"
url = "/portfolio/"
weight = 3

#
[[main]]
name = "Research"
title = "Research"
url = "/research/"
weight = 4

#
[[main]]
name = "Blog"
title = "Blog"
url = "/posts/"
weight = 5

#
[[main]]
name = "Gallery"
title = "My Gallery"
url = "/gallery/"
weight = 6

[[main]]
name = "tags"
title = "Tags"
url = "/tags/"
weight = 7



[[main]]
name = "github"
pre = "github"
url = "https://github.com/KrishnanN27"
weight = 10
